version: '3.9'

networks:
  traefik_savla:
    name: ${DOCKER_NETWORK_NAME}

services:
  hugo_site:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    build:
      args: 
        SITE_NAME: ${APP_NAME}
        APP_ROOT: ${APP_ROOT}
        DOCKER_INTERNAL_PORT: ${DOCKER_INTERNAL_PORT}
      context: hugo/
      dockerfile: Dockerfile
    entrypoint: hugo
    # baseURL is http, because target port is TCP/80
    command: "serve --bind 0.0.0.0 --port ${DOCKER_INTERNAL_PORT} --baseURL https://${APP_URL_MAIN}"
    restart: unless-stopped
    mem_reservation: 128M
    ports:
      - "${DOCKER_EXTERNAL_PORT}:${DOCKER_INTERNAL_PORT}/tcp"
    volumes:
      - "./${APP_NAME}:/site"
    networks:
      - ${DOCKER_NETWORK_NAME}
    labels:
      - "traefik.http.routers.${APP_NAME}.rule=Host(${APP_URLS_TRAEFIK})"
      - "traefik.http.routers.${APP_NAME}.priority=1"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${DOCKER_INTERNAL_PORT}"

