name: hugo silenced CI/CD pipeline

on:
  push:
    branches: [ never ]
  pull_request:
    branches: [ never ]

jobs:

  build:

    runs-on: [ self-hosted, internal, docker ]

    steps:
    - uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag savla-docs:$(date +%s)
      
    - name: Build runtime image
      run: make build

    - name: Redeploy the harp server
      run: make run
