baseURL = 'http://krusty.savla.su'
title = "krusty's space"
theme = "harbor"
languageCode = 'en-uk'

[Params]
    mainSections = ["post"]
    intro = true
    headline = "krusty's space"
    description = "space for my thoughts and prayers"
    github = "https://github.com/krustowski"
    email = "krusty@savla.dev"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
